create_user=https://petstore.swagger.io/v2/user
get_user=https://petstore.swagger.io/v2/user/{username}
update_user=https://petstore.swagger.io/v2/user/{username}
delete_user=https://petstore.swagger.io/v2/user/{username}